name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup mingw64 && building openssl
      run: |
        sudo apt update -y
        sudo apt install -y gcc-mingw-w64 gcc-multilib
        cd openssl-source
        # ./Configure --cross-compile-prefix=x86_64-w64-mingw32- --prefix=$(pwd)/dist --openssldir=/usr/lib/ssl enable-ssl2 enable-ssl3 no-shared mingw64
        ./config --prefix=$(pwd)/dist --openssldir=/usr/lib/ssl enable-ssl2 enable-ssl3 no-shared
        make depend
        make
        sudo make install
        ls -alvh ./dist
        cd ..

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        sudo cp -r ./openssl-source/dist/include/openssl /usr/x86_64-w64-mingw32/include/
        sudo cp -r ./openssl-source/dist/lib/* /usr/x86_64-w64-mingw32/lib/
        # CGO_LDFLAGS="-g -O2 -lwsock32" GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CXX=x86_64-w64-mingw32-g++ CC=x86_64-w64-mingw32-gcc go build -v ./...
        GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -v ./...
